# Generated by Django 6.0.3 on 2026-03-30 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0002_agency_ice_agency_rc'),
        ('contracts', '0003_contractdamage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('Espèce', 'Espèce (Cash)'), ('Chèque', 'Chèque'), ('Virement', 'Virement (Bank Transfer)'), ('TPE', 'TPE (Card)')], default='Espèce', max_length=50, verbose_name='طريقة الدفع')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع (رقم الشيك أو التحويل)')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='agency.agency', verbose_name='الوكالة')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_history', to='contracts.contract', verbose_name='العقد')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المستلم')),
            ],
        ),
    ]
