# Generated by Django 6.0.3 on 2026-03-30 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('clients', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت التسليم')),
                ('date_retour_prevue', models.DateTimeField(verbose_name='تاريخ ووقت الإرجاع المتوقع')),
                ('date_retour_effective', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرجاع الفعلي')),
                ('jours', models.IntegerField(default=1, verbose_name='عدد الأيام')),
                ('km_sortie', models.IntegerField(verbose_name='الكيلومتراج عند الخروج')),
                ('carburant_sortie', models.CharField(choices=[('0', 'فارغ'), ('1/4', 'الربع'), ('1/2', 'النصف'), ('3/4', 'ثلاثة أرباع'), ('1', 'ممتلئ')], default='1/4', max_length=10, verbose_name='الوقود عند الخروج')),
                ('km_retour', models.IntegerField(blank=True, null=True, verbose_name='الكيلومتراج عند الإرجاع')),
                ('carburant_retour', models.CharField(blank=True, choices=[('0', 'فارغ'), ('1/4', 'الربع'), ('1/2', 'النصف'), ('3/4', 'ثلاثة أرباع'), ('1', 'ممتلئ')], max_length=10, null=True, verbose_name='الوقود عند الإرجاع')),
                ('degats_retour', models.TextField(blank=True, null=True, verbose_name='ملاحظات/أضرار عند الإرجاع')),
                ('prix_par_jour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ثمن الكراء اليومي المتفق عليه')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع (التسبيق)')),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المتبقي')),
                ('caution', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الضمانة (Caution)')),
                ('methode_paiement', models.CharField(default='Espèce', max_length=50, verbose_name='طريقة الدفع')),
                ('statut', models.CharField(choices=[('RESERVE', 'محجوزة مسبقاً'), ('EN_COURS', 'في طور الكراء (جارية)'), ('TERMINE', 'منتهية (تم إرجاع السيارة)'), ('ANNULE', 'ملغاة')], default='EN_COURS', max_length=20, verbose_name='حالة العقد')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='agency.agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client', verbose_name='الزبون المكتري')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف الذي أنشأ العقد')),
                ('deuxieme_chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_second', to='clients.client', verbose_name='السائق الثاني')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='fleet.vehicle', verbose_name='السيارة')),
            ],
        ),
    ]
