# Generated by Django 6.0.3 on 2026-03-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cles',
            field=models.BooleanField(default=False, verbose_name='Clés'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cric',
            field=models.BooleanField(default=False, verbose_name='Cric'),
        ),
        migrations.AddField(
            model_name='contract',
            name='degats_depart',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات/أضرار عند الخروج'),
        ),
        migrations.AddField(
            model_name='contract',
            name='extincteur',
            field=models.BooleanField(default=False, verbose_name='Extincteur'),
        ),
        migrations.AddField(
            model_name='contract',
            name='gilet',
            field=models.BooleanField(default=False, verbose_name='Gilet'),
        ),
        migrations.AddField(
            model_name='contract',
            name='manivelle',
            field=models.BooleanField(default=False, verbose_name='Manivelle'),
        ),
        migrations.AddField(
            model_name='contract',
            name='papiers',
            field=models.BooleanField(default=False, verbose_name='Papiers'),
        ),
        migrations.AddField(
            model_name='contract',
            name='roue_secours',
            field=models.BooleanField(default=False, verbose_name='Roue de Secours'),
        ),
        migrations.AddField(
            model_name='contract',
            name='triangle',
            field=models.BooleanField(default=False, verbose_name='Triangle'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='carburant_retour',
            field=models.CharField(blank=True, choices=[('0/8', '0/8 (Vide)'), ('1/8', '1/8'), ('2/8', '2/8 (1/4)'), ('3/8', '3/8'), ('4/8', '4/8 (1/2)'), ('5/8', '5/8'), ('6/8', '6/8 (3/4)'), ('7/8', '7/8'), ('8/8', '8/8 (Plein)')], max_length=10, null=True, verbose_name='الوقود عند الإرجاع'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='carburant_sortie',
            field=models.CharField(choices=[('0/8', '0/8 (Vide)'), ('1/8', '1/8'), ('2/8', '2/8 (1/4)'), ('3/8', '3/8'), ('4/8', '4/8 (1/2)'), ('5/8', '5/8'), ('6/8', '6/8 (3/4)'), ('7/8', '7/8'), ('8/8', '8/8 (Plein)')], default='2/8', max_length=10, verbose_name='الوقود عند الخروج'),
        ),
    ]
