# Generated by Django 6.0.3 on 2026-03-30 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_cles_contract_cric_contract_degats_depart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPART', 'Départ'), ('RETOUR', 'Retour')], default='DEPART', max_length=10)),
                ('x', models.FloatField(verbose_name='الإحداثي X (%)')),
                ('y', models.FloatField(verbose_name='الإحداثي Y (%)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الضرر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='contracts.contract')),
            ],
        ),
    ]
