# Generated by Django 5.2.12 on 2026-07-31 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_id_alter_contractdamage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('contract', 'Contrat'), ('receipt', 'Reçu réservation')], max_length=20)),
                ('with_cachet', models.BooleanField(default=False, verbose_name='Avec cachet')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('READY', 'Prêt'), ('ERROR', 'Erreur')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_jobs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_jobs', to='contracts.contract')),
            ],
        ),
    ]
