# Generated by Django 5.2.12 on 2026-08-02 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_agency_cachet_signature_alter_agency_id_and_more'),
        ('contracts', '0006_pdfjob'),
        ('fleet', '0006_alter_brand_id_alter_modelcar_id_alter_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('date_sortie', models.DateTimeField(verbose_name='Date de sortie souhaitée')),
                ('date_retour_prevue', models.DateTimeField(verbose_name='Date de retour souhaitée')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('CONTACTED', 'Contacté'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='agency.agency', verbose_name='Agence')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='fleet.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
