# Generated by Django 5.2.12 on 2026-08-02 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_alter_customuser_role'),
        ('clients', '0004_client_user_alter_client_agency'),
        ('contracts', '0007_bookingrequest'),
        ('fleet', '0006_alter_brand_id_alter_modelcar_id_alter_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateTimeField(verbose_name='Date de sortie')),
                ('date_retour_prevue', models.DateTimeField(verbose_name='Date de retour prévue')),
                ('prix_par_jour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix par jour')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='agency.agency', verbose_name='Agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clients.client', verbose_name='Client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='fleet.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
