# Generated by Django 5.2.12 on 2026-08-10 17:38

import car_rental_backend.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfjob',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=car_rental_backend.uploads.pdf_job_upload_to),
        ),
    ]
