# Generated by Django 6.0.3 on 2026-03-30 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0002_agency_ice_agency_rc'),
        ('fleet', '0003_brand_alter_vehicle_marque_modelcar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Maintenance', 'صيانة سيارة'), ('Fuel', 'وقود'), ('Salaries', 'رواتب الموظفين'), ('Rent', 'إيجار الوكالة'), ('Utilities', 'كهرباء/ماء/إنترنت'), ('Taxes', 'ضرائب وتأمين'), ('Other', 'مصاريف أخرى')], max_length=50, verbose_name='تصنيف المصروف')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المصروف')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses_receipts/', verbose_name='صورة الوصل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='agency.agency', verbose_name='الوكالة')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسجل')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='fleet.vehicle', verbose_name='السيارة (اختياري)')),
            ],
        ),
    ]
