# Generated by Django 5.2.12 on 2026-08-10 17:38

import car_rental_backend.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=car_rental_backend.uploads.expense_receipt_upload_to, verbose_name='صورة الوصل'),
        ),
    ]
