# Generated by Django 6.0.3 on 2026-03-30 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_passport', models.CharField(max_length=20, unique=True, verbose_name='رقم البطاقة الوطنية أو الجواز')),
                ('nom', models.CharField(max_length=50, verbose_name='الاسم العائلي')),
                ('prenom', models.CharField(max_length=50, verbose_name='الاسم الشخصي')),
                ('telephone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('permis_conduite', models.CharField(max_length=50, unique=True, verbose_name='رقم رخصة السياقة')),
                ('date_delivrance_permis', models.DateField(blank=True, null=True, verbose_name='تاريخ تسليم رخصة السياقة')),
                ('adresse', models.TextField(verbose_name='العنوان')),
                ('liste_noire', models.BooleanField(default=False, verbose_name='في القائمة السوداء؟')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='ملاحظات حول الزبون')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='agency.agency')),
            ],
            options={
                'unique_together': {('agency', 'cin_passport')},
            },
        ),
    ]
