# Generated by Django 5.2.12 on 2026-08-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_optional_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
    ]
