# Generated by Django 5.2.12 on 2026-08-10 17:38

import car_rental_backend.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='scan_cin',
            field=models.ImageField(blank=True, null=True, upload_to=car_rental_backend.uploads.client_document_upload_cin, verbose_name='صورة البطاقة الوطنية/الجواز'),
        ),
        migrations.AlterField(
            model_name='client',
            name='scan_permis',
            field=models.ImageField(blank=True, null=True, upload_to=car_rental_backend.uploads.client_document_upload_permis, verbose_name='صورة رخصة السياقة'),
        ),
    ]
