# Generated by Django 5.2.12

import car_rental_backend.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_scan_cin_alter_client_scan_permis'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=car_rental_backend.uploads.client_photo_upload, verbose_name='صورة الملف الشخصي'),
        ),
    ]
