# Generated by Django 6.0.3 on 2026-03-30 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='رقم الترقيم')),
                ('marque', models.CharField(max_length=50, verbose_name='العلامة التجارية')),
                ('modele', models.CharField(max_length=50, verbose_name='الموديل')),
                ('annee', models.IntegerField(verbose_name='سنة الصنع')),
                ('couleur', models.CharField(max_length=30, verbose_name='اللون')),
                ('carburant', models.CharField(choices=[('Diesel', 'ديزل'), ('Essence', 'بنزين'), ('Hybride', 'هجين'), ('Electrique', 'كهربائي')], max_length=20, verbose_name='نوع الوقود')),
                ('kilometrage', models.IntegerField(verbose_name='الكيلومترات الحالية')),
                ('prix_par_jour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ثمن الكراء اليومي')),
                ('statut', models.CharField(choices=[('Available', 'متاحة'), ('Rented', 'مكتراة'), ('Maintenance', 'في الصيانة')], default='Available', max_length=20, verbose_name='حالة السيارة')),
                ('date_assurance', models.DateField(verbose_name='تاريخ انتهاء التأمين')),
                ('date_visite_technique', models.DateField(verbose_name='تاريخ انتهاء الفحص التقني')),
                ('prochain_vidange_km', models.IntegerField(verbose_name='الكيلومتراج القادم لتغيير الزيت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles_images/')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='agency.agency')),
            ],
        ),
    ]
