# Generated by Django 6.0.3 on 2026-03-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chauffeur_disponible',
            field=models.BooleanField(default=False, verbose_name='سائق متوفر'),
        ),
    ]
