# Generated by Django 6.0.3 on 2026-04-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_modelcar_options_alter_brand_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tarif_km_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tarif km supplémentaire (DH/km)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modelcar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
