# Generated by Django 5.2.12 on 2026-08-08 21:12

import fleet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_alter_evaluation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=fleet.models.vehicle_image_upload_to),
        ),
    ]
