# Generated by Django 5.2.12 on 2026-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_alter_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='traccar_device_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID dispositif Traccar'),
        ),
    ]
