# Generated by Django 5.2.12 on 2026-08-14 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_normalize_vehicle_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date_autorisation_circulation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'autorisation de circulation"),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_mise_en_circulation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de mise en circulation'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='matricule_definitif',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matricule définitif (00000-lettre-00)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puissance_fiscale',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Puissance fiscale (CV)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='prix_par_jour',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix par jour (défaut)'),
        ),
        migrations.CreateModel(
            name='VehiclePriceInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECURRENT', 'Récurrent (chaque année)'), ('ABSOLUTE', 'Absolu (dates précises)')], default='RECURRENT', max_length=20, verbose_name='Type')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix journalier (DH)')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('mois_debut', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mois de début (1-12)')),
                ('jour_debut', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jour de début (1-31)')),
                ('mois_fin', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mois de fin (1-12)')),
                ('jour_fin', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jour de fin (1-31)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_intervals', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Période tarifaire',
                'verbose_name_plural': 'Périodes tarifaires',
                'ordering': ['type', 'date_debut', 'mois_debut'],
            },
        ),
    ]
