"use client"

import { useState } from "react"
import { Bell, CarFront, ChevronDown, CircleHelp, ClipboardList, FileText, LayoutDashboard, MapPin, Menu, MoreHorizontal, Search, Settings, ShieldAlert, Users, WalletCards, X } from "lucide-react"

const nav = [
  { label: "Vue d’ensemble", icon: LayoutDashboard }, { label: "Flotte automobile", icon: CarFront }, { label: "Contrats", icon: FileText }, { label: "Clients", icon: Users }, { label: "Réservations", icon: ClipboardList }, { label: "Paiements", icon: WalletCards }, { label: "Suivi GPS", icon: MapPin },
]
const contracts = [{ client: "Yassine El Mansouri", vehicle: "Dacia Logan · 4821-A-16", amount: "4 250 MAD", status: "En cours", date: "Aujourd’hui, 09:42", initials: "YE" }, { client: "Nadia Benali", vehicle: "Volkswagen T-Roc · 7110-B-8", amount: "8 600 MAD", status: "Réservé", date: "Hier, 16:20", initials: "NB" }, { client: "Omar Alaoui", vehicle: "Renault Clio · 2304-C-12", amount: "2 100 MAD", status: "Terminé", date: "12 sept. 2025", initials: "OA" }, { client: "Sofia Berrada", vehicle: "Hyundai Tucson · 5890-D-4", amount: "6 750 MAD", status: "En cours", date: "11 sept. 2025", initials: "SB" }]

function Status({ children }: { children: string }) { const styles: Record<string, string> = { "En cours": "bg-[#e8f7ef] text-[#168052]", Réservé: "bg-[#fff4dd] text-[#aa741c]", Terminé: "bg-[#eef1f5] text-[#667085]" }; return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${styles[children]}`}>{children}</span> }
function Kpi({ icon: Icon, label, value, trend, tone }: { icon: any; label: string; value: string; trend: string; tone: string }) { return <div className="rounded-2xl border border-[#e6eaf0] bg-white p-5 shadow-[0_2px_10px_rgba(24,38,60,.03)]"><div className="flex items-start justify-between"><div className={`flex size-10 items-center justify-center rounded-xl ${tone}`}><Icon size={19} /></div><span className="rounded-full bg-[#e8f7ef] px-2 py-1 text-[11px] font-bold text-[#168052]">{trend}</span></div><p className="mt-5 text-sm text-[#667085]">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight text-[#172033]">{value}</p></div> }

export default function Dashboard() {
  const [active, setActive] = useState("Vue d’ensemble")
  const [lang, setLang] = useState("FR")
  const [mobile, setMobile] = useState(false)
  return <main className="min-h-screen bg-[#f6f8fb] text-[#172033]">
    <aside className={`fixed inset-y-0 left-0 z-20 flex w-[248px] flex-col border-r border-[#e6eaf0] bg-white px-4 py-5 transition-transform lg:translate-x-0 ${mobile ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-center justify-between px-3"><div className="flex items-center gap-2.5"><div className="flex size-9 items-center justify-center rounded-xl bg-[#132238] text-sm font-black text-white">K</div><div><p className="text-[15px] font-extrabold tracking-tight">Kriniback</p><p className="text-[10px] font-medium uppercase tracking-[.16em] text-[#98a2b3]">Agency OS</p></div></div><button onClick={() => setMobile(false)} className="lg:hidden"><X size={18}/></button></div>
      <div className="mt-10 flex flex-col gap-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobile(false) }} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[13px] font-semibold transition ${active === label ? "bg-[#edf4ff] text-[#2672e8]" : "text-[#667085] hover:bg-[#f6f8fb] hover:text-[#172033]"}`}><Icon size={18}/>{label}{label === "Réservations" && <span className="ml-auto rounded-md bg-[#2672e8] px-1.5 py-0.5 text-[10px] text-white">3</span>}</button>)}</div>
      <div className="mt-auto rounded-2xl bg-[#f6f8fb] p-4"><div className="mb-3 flex size-8 items-center justify-center rounded-lg bg-white text-[#2672e8] shadow-sm"><CircleHelp size={17}/></div><p className="text-xs font-bold">Besoin d’aide ?</p><p className="mt-1 text-[11px] leading-5 text-[#667085]">Notre équipe est disponible pour vous accompagner.</p><button className="mt-3 text-[11px] font-bold text-[#2672e8]">Centre d’aide →</button></div>
      <div className="mt-4 flex items-center gap-3 border-t border-[#e6eaf0] px-3 pt-4"><div className="flex size-8 items-center justify-center rounded-full bg-[#d9e8ff] text-[11px] font-bold text-[#2672e8]">AM</div><div className="min-w-0"><p className="truncate text-xs font-bold">Agence MobiRent</p><p className="text-[10px] text-[#98a2b3]">Administrateur</p></div><Settings className="ml-auto text-[#98a2b3]" size={15}/></div>
    </aside>
    {mobile && <button aria-label="Fermer le menu" onClick={() => setMobile(false)} className="fixed inset-0 z-10 bg-[#132238]/20 lg:hidden"/>}
    <section className="lg:pl-[248px]"><header className="sticky top-0 z-10 flex h-[72px] items-center justify-between border-b border-[#e6eaf0] bg-white/90 px-5 backdrop-blur-md md:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobile(true)} className="lg:hidden"><Menu size={22}/></button><div className="hidden items-center gap-2 rounded-xl bg-[#f6f8fb] px-3 py-2.5 text-xs text-[#98a2b3] md:flex md:w-[260px]"><Search size={16}/><span>Rechercher...</span><kbd className="ml-auto rounded border border-[#e6eaf0] bg-white px-1.5 py-0.5 text-[10px]">⌘ K</kbd></div></div><div className="flex items-center gap-4"><button onClick={() => setLang(lang === "FR" ? "AR" : "FR")} className="rounded-lg border border-[#e6eaf0] px-2.5 py-1.5 text-[11px] font-bold text-[#667085]">{lang} <ChevronDown size={12} className="ml-1 inline"/></button><button className="relative text-[#667085]"><Bell size={19}/><span className="absolute -right-1 -top-1 size-2 rounded-full bg-[#d65c62]"/></button><div className="hidden h-7 w-px bg-[#e6eaf0] sm:block"/><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-full bg-[#132238] text-[11px] font-bold text-white">AM</div><span className="hidden text-xs font-bold sm:block">Amina M.</span></div></div></header>
    <div className="mx-auto max-w-[1400px] p-5 md:p-8"><div className="animate-rise flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#2672e8]">Lundi, 15 septembre 2025</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight md:text-[34px]">Bonjour Amina <span className="font-normal">—</span> <span className="text-[#667085]">voici votre activité.</span></h1><p className="mt-2 text-sm text-[#667085]">Tout ce qui se passe dans votre agence, en un coup d’œil.</p></div><button className="flex w-fit items-center gap-2 rounded-xl bg-[#2672e8] px-4 py-2.5 text-xs font-bold text-white shadow-[0_6px_16px_rgba(38,114,232,.2)]"><span className="text-base">+</span> Nouveau contrat</button></div>
      <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={CarFront} label="Véhicules dans la flotte" value="48" trend="+4,2%" tone="bg-[#eaf2ff] text-[#2672e8]"/><Kpi icon={FileText} label="Contrats actifs" value="17" trend="+2 ce mois" tone="bg-[#e8f7ef] text-[#168052]"/><Kpi icon={Users} label="Clients enregistrés" value="284" trend="+12,5%" tone="bg-[#fff4dd] text-[#aa741c]"/><Kpi icon={WalletCards} label="Revenus ce mois" value="86 420 MAD" trend="+18,7%" tone="bg-[#f2ecff] text-[#7756c9]"/></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="animate-rise delay-1 rounded-2xl border border-[#e6eaf0] bg-white p-5 shadow-[0_2px_10px_rgba(24,38,60,.03)]"><div className="flex items-center justify-between"><div><h2 className="font-bold">Activité de la flotte</h2><p className="mt-1 text-xs text-[#98a2b3]">Répartition actuelle de vos véhicules</p></div><button className="text-[#98a2b3]"><MoreHorizontal size={19}/></button></div><div className="mt-7 flex items-center gap-8"><div className="relative flex size-[150px] shrink-0 items-center justify-center rounded-full" style={{background:"conic-gradient(#2672e8 0 46%, #27a66f 46% 77%, #e5a631 77% 88%, #e8edf3 88% 100%)"}}><div className="flex size-[108px] flex-col items-center justify-center rounded-full bg-white"><span className="text-2xl font-extrabold">48</span><span className="text-[10px] text-[#98a2b3]">véhicules</span></div></div><div className="flex flex-1 flex-col gap-4">{[["Disponible","22 véhicules","#2672e8"],["En location","15 véhicules","#27a66f"],["Maintenance","5 véhicules","#e5a631"],["Hors service","6 véhicules","#d5dae2"]].map(([a,b,c]) => <div className="flex items-center gap-3" key={a}><span className="size-2.5 rounded-full" style={{background:c}}/><span className="text-xs text-[#667085]">{a}</span><strong className="ml-auto text-xs">{b}</strong></div>)}</div></div></div>
      <div className="animate-rise delay-2 rounded-2xl border border-[#e6eaf0] bg-[#132238] p-6 text-white"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#8db6ff]">À surveiller</p><h2 className="mt-2 text-xl font-bold">Alertes administratives</h2></div><div className="flex size-9 items-center justify-center rounded-xl bg-white/10"><ShieldAlert size={18} className="text-[#8db6ff]"/></div></div><div className="mt-6 flex flex-col gap-3"><div className="flex items-center gap-3 rounded-xl bg-white/8 p-3"><div className="flex size-8 items-center justify-center rounded-lg bg-[#e5a631]/20 text-[#f2bd57]"><ShieldAlert size={15}/></div><div><p className="text-xs font-bold">Assurance à renouveler</p><p className="mt-1 text-[10px] text-[#aab8ca]">3 véhicules concernés</p></div><ChevronDown className="ml-auto -rotate-90 text-[#8d9caf]" size={15}/></div><div className="flex items-center gap-3 rounded-xl bg-white/8 p-3"><div className="flex size-8 items-center justify-center rounded-lg bg-[#d65c62]/20 text-[#f0797d]"><CarFront size={15}/></div><div><p className="text-xs font-bold">Visite technique</p><p className="mt-1 text-[10px] text-[#aab8ca]">2 échéances cette semaine</p></div><ChevronDown className="ml-auto -rotate-90 text-[#8d9caf]" size={15}/></div></div><button className="mt-5 text-xs font-bold text-[#8db6ff]">Voir toutes les alertes →</button></div></div>
      <div className="animate-rise delay-3 mt-6 rounded-2xl border border-[#e6eaf0] bg-white shadow-[0_2px_10px_rgba(24,38,60,.03)]"><div className="flex flex-col justify-between gap-3 border-b border-[#e6eaf0] p-5 sm:flex-row sm:items-center"><div><h2 className="font-bold">Contrats récents</h2><p className="mt-1 text-xs text-[#98a2b3]">Les dernières opérations de votre agence</p></div><button className="w-fit rounded-lg border border-[#e6eaf0] px-3 py-2 text-xs font-bold text-[#2672e8]">Voir tous les contrats</button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="border-b border-[#f0f2f5] text-[10px] uppercase tracking-wider text-[#98a2b3]"><th className="px-5 py-3 font-bold">Client</th><th className="px-5 py-3 font-bold">Véhicule</th><th className="px-5 py-3 font-bold">Montant</th><th className="px-5 py-3 font-bold">Statut</th><th className="px-5 py-3 font-bold">Date</th><th/></tr></thead><tbody>{contracts.map(c => <tr key={c.client} className="border-b border-[#f0f2f5] last:border-0 hover:bg-[#fbfcfe]"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-full bg-[#edf4ff] text-[10px] font-bold text-[#2672e8]">{c.initials}</div><span className="text-xs font-bold">{c.client}</span></div></td><td className="px-5 py-4 text-xs text-[#667085]">{c.vehicle}</td><td className="px-5 py-4 text-xs font-bold">{c.amount}</td><td className="px-5 py-4"><Status>{c.status}</Status></td><td className="px-5 py-4 text-xs text-[#667085]">{c.date}</td><td className="px-5 py-4 text-right"><button className="text-[#98a2b3]"><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div></div>
    </div></section>
  </main>
}
