# Generated by Django 6.0.3 on 2026-03-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='ice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التعريف الموحد (ICE)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='rc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم التجاري (RC)'),
        ),
    ]
