# Generated by Django 5.2.12 on 2026-08-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_agency_cachet_signature_alter_agency_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Gérant / Propriétaire'), ('EMPLOYEE', 'Employé'), ('CLIENT', 'Client')], default='EMPLOYEE', max_length=20, verbose_name='Rôle'),
        ),
    ]
