# Generated by Django 5.2.12 on 2026-08-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_alter_customuser_role'),
        ('fleet', '0006_alter_brand_id_alter_modelcar_id_alter_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='agencies', to='fleet.brand', verbose_name='Marques affichées'),
        ),
    ]
