# Generated by Django 5.2.12 on 2026-08-08 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_agency_pays_agency_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='pays',
        ),
    ]
