# Generated by Django 5.2.12 on 2026-08-08 21:12

import agency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_remove_agency_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='cachet_signature',
            field=models.ImageField(blank=True, null=True, upload_to=agency.models.agency_cachet_upload_to, verbose_name='Cachet et Signature'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=agency.models.agency_logo_upload_to),
        ),
    ]
