# Generated by Django 5.2.12 on 2026-08-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='location_buffer_hours',
            field=models.DecimalField(decimal_places=0, default=2, help_text="Heures d'indisponibilité supplémentaires avant et après chaque location.", max_digits=4, verbose_name='Délai de confort (heures)'),
        ),
    ]
